# Test integration
version: '3'
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "P455W0Rd"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  colorapi:
    build: .
    environment: 
      DBserver: "ms-sql-server"
      DBport: "1433"
      DBuser: "SA"
      DBpass: "P455W0Rd"
      Database: "Colors"
    ports: 
      - "80:80"
